# 1. install python on ubuntu 16.04
# 2. install basic packages
# 3. setup firewall
# 4. add devops admin user account
- include: basic_server_setup.yml

# 5. install rmagick dependencies
- include: rmagic_dependencies.yml

# 6. create deployer user account
- include: deployer.yml

# 7. install ntp
# 8. install nginx
- include: ntp_nginx.yml

# 9. configure nginx
- include: nginx_config.yml

# 10. install systemd files for puma and sidekiq
- include: puma_service.yml
- include: sidekiq_service.yml

# 11. install rbenv & install bundler gem
- include: rbenv.yml

# 12. install postgresql
- include: postgresql.yml

# 13. make shared directory for capistrano
# 14. deploy rails config files into shared directory
- include: deploy_rails_config.yml
