---
- name: "install and setup ntp"
  include_role:
    name: ansible-role-ntp
    vars:
      ntp_enabled: true
- name: "install nginx"
  include_role:
    name: ansible-role-nginx
    vars:
      nginx_sites:
        default:
          - listen 80
          - server_name _
          - root "{% if ansible_os_family == 'FreeBSD' %}/usr/local/www/nginx-dist{% else %}/usr/share/nginx/html{% endif %}"
          - index index.html
      nginx_remove_sites:
        - 'default'
        - 'default.conf'
