---
- name: "Install python-psycopg2"
  apt:
    name: python-psycopg2
    state: installed

- name: "Install postgresql"
  apt:
    name: postgresql
    state: installed

- name: "Create database"
  postgresql_db: name={{database.name}}
                encoding=UTF-8
  become: true
  become_user: postgres

- name: "Create DB user"
  postgresql_user: db={{database.name}}
                  name={{database.username}}
                  password={{database.password}}
                  role_attr_flags=CREATEDB,SUPERUSER
  become: true
  become_user: postgres
