---
- name: "Install rbenv, plugins and rubies"
  include_role:
    name: zzet.ansible-rbenv-role
  vars:
    rbenv_repo: "https://github.com/rbenv/rbenv.git"
    rbenv:
      env: user
      version: v1.1.0
      default_ruby: 2.3.3
      rubies:
        - version: 2.3.3
    rbenv_root: "{% if rbenv.env == 'system' %}/usr/local/rbenv{% else %}{{deployer.home_dir}}/.rbenv{% endif %}"
    rbenv_users:
      - "{{ deployer.username }}"
    rbenv_plugins:
      - { name: "rbenv-vars",
          repo: "https://github.com/rbenv/rbenv-vars.git",
          version: "v1.2.0" }

      - { name: "ruby-build",
          repo: "https://github.com/rbenv/ruby-build.git",
          version: "master" }

      - { name: "rbenv-default-gems",
          repo: "https://github.com/viatcheslavmogilevsky/rbenv-default-gems.git",
          version: "v1.0.0" }

      - { name: "rbenv-installer",
          repo: "https://github.com/rbenv/rbenv-installer.git",
          version: "bc21e7055dcc8f5f9bc66ce0c78cc9ae0c28cd7a" }

      - { name: "rbenv-update",
          repo: "https://github.com/rkh/rbenv-update.git",
          version: "1961fa180280bb50b64cbbffe6a5df7cf70f5e50" }

      - { name: "rbenv-whatis",
          repo: "https://github.com/rkh/rbenv-whatis.git",
          version: "v1.0.0" }

      - { name: "rbenv-use",
          repo: "https://github.com/rkh/rbenv-use.git",
          version: "v1.0.0" }

# install bundler
- name: Install Bundler
  become: true
  become_user: "{{ deployer.username }}"
  command: bash -lc "gem install bundler"
