---
- name: "purge imagemagick related packages"
  apt:
    state: absent
    purge: yes
    force: yes
  vars:
    packages:
      - graphicsmagick
      - graphicsmagick-dbg
      - imagemagick-common
      - imagemagick
      - imagemagick-6.q16
      - libmagickcore-6-headers
      - libmagickwand-dev
      - graphicsmagick-libmagick-dev-compat

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: 'install imagemagick and libmagickwand-dev'
  apt:
    update_cache: yes
  vars:
    packages:
      - imagemagick
      - libmagickwand-dev
